apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: varun029/mynextapp:07
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          env:
            - name: DATABASE_URL
              value: "mongodb+srv://varun:29112002VrB@cluster0.c81dkme.mongodb.net/events-check-in?retryWrites=true&w=majority"
            - name: NEXT_PUBLIC_QR_SECRET_KEY
              value: "121ejknnwe9r7489rhejfwanfwio"
            - name: NEXT_PUBLIC_BASE_URL
              value: "http://192.168.0.100:3000"
            - name: NEXT_GEOLOCATION_API
              value: "pk.172cef7453a6d5867cfb00259baf81ed"
          volumeMounts:
            - name: qrcodes-volume
              mountPath: /app/public/qrcodes
            - name: attendanceqrcodes-volume
              mountPath: /app/public/attendanceqrcodes
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: qrcodes-volume
          persistentVolumeClaim:
            claimName: qrcodes-pvc
        - name: attendanceqrcodes-volume
          persistentVolumeClaim:
            claimName: attendanceqrcodes-pvc
