apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: varun029/mynextjsapp:01
          ports:
            - containerPort: 3000
